# Site settings
title: Vinni Works!
email: vineelajagana@gmail.com
description: "WELCOME to my personal website!  Thanks for visiting, and please come back, because i update this page frequently."
baseurl: ""
baseurlPosts: "/vinniblogsite"
url: "http://miluonline.github.io/vinniblogsite"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
