# Site settings
title: Vinni Works!
email: vineelajagana@gmail.com
description: "WELCOME to my personal website!  Thanks for visiting, and please come back, because i update this page frequently."
baseurl: "/vinniblogsite"
baseurlPosts: ""
url: "http://miluonline.github.io"
twitter_username: jekyllrb
github_username:  jekyll
paginate: 5

# Build settings
markdown: kramdown
permalink: pretty
